### ISSUE TITLE
Option for deepcopy of arguments when using addStep

### ISSUE THREAD

**Issue by zantonas** [lexsca/rollback#1]
I'd like to add a deepcopy option for rollback arguments. When passing mutable arguments to the addStep function, if those arguments change outside of the time in which the rollback is triggered, it also changes the expected outcome of that rollback step. It would be helpful to provide a deep copy option to the addStep function to avoid this case.

I'd be happy to help submit a pull request but will require collaboration rights. Would you prefer I add this option to the constructor or to the addStep function?

def __init__(self, onError=False, onSuccess=False, raiseError=True, **deepCopyArgs=False**)
or 
def addStep(self, callback, *args, **kwargs, **deepCopyArgs=False**)

**Comment by lexsca** [comment]
sorry for the delay.  just noticed this.  if the arguments passed to `addStep` are mutable and likely to change, the caller should probably be the one to do a deep copy.  doing a deep copy in rollback seems a bit fiddly.  if it were down to me, i'd probably subclass rollback in whatever project needed a deep copy or fork rollback as a last resort.

**Comment by zantonas** [comment]
We do some (probably not good) value switching with some variables before a rollback is triggered, which makes this a little more tricky for us. However that's a fair point regarding the caller, so I'm closing this request. I appreciate the response
